/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuladorsgemx;

import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    private ImageIcon img;
    private TrayIcon TrIc;
    private SystemTray SysTr;
    
    public Menu() {
        img = new ImageIcon(this.getClass().getResource("/img/sge.png"));
        initComponents();
        this.setIconImage(img.getImage());
        instanciarTray();
    }
    private void instanciarTray(){
        TrIc = new TrayIcon(img.getImage(), "Emulador SGEMX API", popup);
        TrIc.setImageAutoSize(true);
        SysTr = SystemTray.getSystemTray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new java.awt.PopupMenu();
        Abrir = new java.awt.MenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        Detener = new javax.swing.JButton();
        Script1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        popup.setLabel("popupMenu1");

        Abrir.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Abrir.setLabel("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        popup.add(Abrir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGEMX APIS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Emulador API SGEMX");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton1.setText("Minimizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, -1));

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, -1));

        Detener.setText("Detener");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });
        getContentPane().add(Detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 80, -1));

        Script1.setBackground(new java.awt.Color(0, 204, 0));
        Script1.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(Script1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, -1));

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if (SystemTray.isSupported()) {
                SysTr.add(TrIc);
                this.setVisible(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        SysTr.remove(TrIc);
        this.setVisible(true);
    }//GEN-LAST:event_AbrirActionPerformed
Proceso hilo1 = new Proceso("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/1.php");
Proceso_Sec hilo1_1 = new Proceso_Sec("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/1.php");
Proceso hilo2 = new Proceso("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/2.php");
Proceso_Sec hilo2_2 = new Proceso_Sec("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/2.php");
Proceso hilo3 = new Proceso("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/3.php");
Proceso_Sec hilo3_3 = new Proceso_Sec("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/3.php");
Proceso hilo4 = new Proceso("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/4.php");
Proceso_Sec hilo4_4 = new Proceso_Sec("cmd /c C://EmuladorSGEMX/php/php.exe C://EmuladorSGEMX/php/4.php");
boolean status = true;
    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        Script1.setValue(100);
        try{
            if(status){
                hilo1.start();
                hilo1_1.start();
                hilo2.start();
                hilo2_2.start();
                hilo3.start();
                hilo3_3.start();
                hilo4.start();
                hilo4_4.start();
            }else{
                hilo1.resume();
                hilo1_1.resume();
                hilo2.resume();
                hilo2_2.resume();
                hilo3.resume();
                hilo3_3.resume();
                hilo4.resume();
                hilo4_4.resume();

            }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        
       
    }//GEN-LAST:event_IniciarActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
        hilo1.suspend();
        hilo1_1.suspend();
        hilo2.suspend();
        hilo2_2.suspend();
        hilo3.suspend();
        hilo3_3.suspend();
        hilo4.suspend();
        hilo4_4.suspend();
        status = false;
        Script1.setValue(0);
        System.out.println("Procesos Detenidos...");
        try{
                Process process = Runtime.getRuntime().exec("cmd /c taskkill /f /im php.exe");
                InputStreamReader entrada = new InputStreamReader(process.getInputStream());
                BufferedReader salida = new BufferedReader(entrada);
                String i = null;
                while ((i = salida.readLine()) != null){
                    //JOptionPane.showMessageDialog(null, i);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            } 
    }//GEN-LAST:event_DetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.MenuItem Abrir;
    private javax.swing.JButton Detener;
    private javax.swing.JButton Iniciar;
    public javax.swing.JProgressBar Script1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.PopupMenu popup;
    // End of variables declaration//GEN-END:variables
}
